spring:
  application:
    name: payment
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:2222

resilience4j.circuitbreaker:
  instances:
    paymentCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
